services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://pvara-backend.fortanixor.com
    ports:
      - "6076:80"
    restart: unless-stopped
    container_name: pvara-frontend
